version: 1.0.0
services:
  - mysql
events:
  build:
    steps:
      - build:
          type: script
          script:
            - nvm install 5.6.0
            - nvm use 5.6.0
            - curl -o- -L https://yarnpkg.com/install.sh | bash
            - export PATH=$HOME/.yarn/bin:$PATH
            - composer install --prefer-source
            - mysql -e 'CREATE DATABASE drupal;'
