version: '3.2'
services:
  drupal:
    build:
      context: .
      dockerfile: dockerfiles/drupal
    ports:
    - "8888:80"
    - "8889:80"
    volumes:
    - .:/host-repo:cached
    - ~/.acquia:/root/.acquia
    - ~/.drush:/root/.drush
    - ~/.ssh:/root/host-ssh
    environment:
    - DRUPAL_DATABASE_HOST=mysql
  mysql:
    build:
      context: .
      dockerfile: dockerfiles/mysql
    command: 
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb-buffer-pool-size=256M"
      - "--key-buffer-size=10M" 
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
