<?php

/**
 * @file
 * Migrates field_related_content data to appropriate entity reference.
 */

/*
 * Implements hook_action_info().
 */
function bos_related_content_migration_action_info() {
  return array(
    'bos_related_content_migration_action' => array(
      'type' => 'node',
      'label' => t('Rel Content Mig'),
      'behavior' => array('changes_property'),
      'triggers' => array('any'),
      'configurable' => FALSE,
    ),
  );
}

/*
 * Action callback for VBO.
 */
function bos_related_content_migration_action(&$entity, $context) {

  foreach ($entity->field_related_content[$entity->language] as $key => $value) {

    if (isset($value['target_id'])) {

      $referenced_nid = $value['target_id'];
      $referenced_node = node_load($referenced_nid);
      $referenced_node_type = $referenced_node->type;

      switch ($referenced_node_type) {

        case 'place_profile':
          $entity->field_place[$entity->language][]['target_id'] = $value['target_id'];
          unset($entity->field_related_content['und'][$key]);
          break;

        case 'program_initiative_profile':
          $entity->field_program_initiative[$entity->language][]['target_id'] = $value['target_id'];
          unset($entity->field_related_content['und'][$key]);
          break;

        case 'person_profile':
          $entity->field_people[$entity->language][]['target_id'] = $value['target_id'];
          unset($entity->field_related_content['und'][$key]);
          break;

        case 'event':
        case 'public_notice':
          $entity->field_related_events_notices[$entity->language][]['target_id'] = $value['target_id'];
          unset($entity->field_related_content['und'][$key]);
          break;

        case 'post':
          $entity->field_related_posts[$entity->language][]['target_id'] = $value['target_id'];
          unset($entity->field_related_content['und'][$key]);
          break;

        case 'topic_page':
          $entity->field_related_guides[$entity->language][]['target_id'] = $value['target_id'];
          unset($entity->field_related_content['und'][$key]);
          break;

        default:
          break;
      }
    }
  }
  node_save($entity);
}
