<?php

/**
 * @file
 * Permissions.settings.php.
 *
 * Implements acquia_permissions_map which provides the full list of drush-
 * generated roles/permissions used on the website. Keeping permissions
 * outside of features is preferrable as it gets extremely messy with
 * dependencies.
 */

/**
 * Function acquia_permissions_map().
 *
 * Implements acquia_permissions_map which contains a list of drush-generated
 * roles and permissions.
 */
function acquia_permissions_map() {
  return array(
    // Anonymous user role permissions.
    'anonymous user' => array(
      'access content',
      'view files',
      'vote on polls',
      'view paragraph content 3_column_w_image',
      'view paragraph content bid',
      'view paragraph content bos_signup_emergency_alerts',
      'view paragraph content bos311',
      'view paragraph content cabinet',
      'view paragraph content card',
      'view paragraph content city_score_dashboard',
      'view paragraph content custom_hours_text',
      'view paragraph content daily_hours',
      'view paragraph content discussion_topic',
      'view paragraph content document',
      'view paragraph content drawer',
      'view paragraph content drawers',
      'view paragraph content election_results',
      'view paragraph content external_link',
      'view paragraph content featured_item',
      'view paragraph content featured_topics',
      'view paragraph content feedback',
      'view paragraph content fyi',
      'view paragraph content gol_list_links',
      'view paragraph content grid_of_cards',
      'view paragraph content grid_of_people',
      'view paragraph content grid_of_places',
      'view paragraph content grid_of_programs_initiatives',
      'view paragraph content grid_of_quotes',
      'view paragraph content grid_of_topics',
      'view paragraph content group_of_links_grid',
      'view paragraph content group_of_links_list',
      'view paragraph content group_of_links_mini_grid',
      'view paragraph content header_text',
      'view paragraph content hero_image',
      'view paragraph content how_to_contact_step',
      'view paragraph content how_to_tab',
      'view paragraph content how_to_text_step',
      'view paragraph content iframe',
      'view paragraph content internal_link',
      'view paragraph content list',
      'view paragraph content map',
      'view paragraph content map_coordinates',
      'view paragraph content map_esri_feed',
      'view paragraph content map_pin',
      'view paragraph content message_for_the_day',
      'view paragraph content news_announcements',
      'view paragraph content newsletter',
      'view paragraph content photo',
      'view paragraph content quote',
      'view paragraph content recollect_widget',
      'view paragraph content script_embed',
      'view paragraph content seamless_doc',
      'view paragraph content sidebar_item',
      'view paragraph content sidebar_item_w_icon',
      'view paragraph content social_media_links',
      'view paragraph content social_networking',
      'view paragraph content status_override',
      'view paragraph content tabbed_content_tab',
      'view paragraph content text',
      'view paragraph content text_one_column',
      'view paragraph content text_three_column',
      'view paragraph content text_two_column',
      'view paragraph content transaction_grid',
      'view paragraph content upcoming_events',
      'view paragraph content user_action',
      'view paragraph content video',
    ),
    // Authenticated user role permissions.
    'authenticated user' => array(
      'access administration menu',
      'access administration pages',
      'access content',
      'access keyboard shortcuts',
      'create paragraph content 3_column_w_image',
      'create paragraph content bid',
      'create paragraph content bos_signup_emergency_alerts',
      'create paragraph content bos311',
      'create paragraph content cabinet',
      'create paragraph content card',
      'create paragraph content city_score_dashboard',
      'create paragraph content custom_hours_text',
      'create paragraph content daily_hours',
      'create paragraph content discussion_topic',
      'create paragraph content document',
      'create paragraph content drawer',
      'create paragraph content drawers',
      'create paragraph content election_results',
      'create paragraph content external_link',
      'create paragraph content featured_item',
      'create paragraph content featured_topics',
      'create paragraph content feedback',
      'create paragraph content fyi',
      'create paragraph content gol_list_links',
      'create paragraph content grid_of_cards',
      'create paragraph content grid_of_people',
      'create paragraph content grid_of_places',
      'create paragraph content grid_of_programs_initiatives',
      'create paragraph content grid_of_quotes',
      'create paragraph content grid_of_topics',
      'create paragraph content group_of_links_grid',
      'create paragraph content group_of_links_list',
      'create paragraph content group_of_links_mini_grid',
      'create paragraph content header_text',
      'create paragraph content hero_image',
      'create paragraph content how_to_contact_step',
      'create paragraph content how_to_tab',
      'create paragraph content how_to_text_step',
      'create paragraph content iframe',
      'create paragraph content internal_link',
      'create paragraph content list',
      'create paragraph content map',
      'create paragraph content map_coordinates',
      'create paragraph content map_esri_feed',
      'create paragraph content map_pin',
      'create paragraph content message_for_the_day',
      'create paragraph content news_announcements',
      'create paragraph content newsletter',
      'create paragraph content photo',
      'create paragraph content quote',
      'create paragraph content recollect_widget',
      'create paragraph content script_embed',
      'create paragraph content seamless_doc',
      'create paragraph content sidebar_item',
      'create paragraph content sidebar_item_w_icon',
      'create paragraph content social_media_links',
      'create paragraph content social_networking',
      'create paragraph content status_override',
      'create paragraph content tabbed_content_tab',
      'create paragraph content text',
      'create paragraph content text_one_column',
      'create paragraph content text_three_column',
      'create paragraph content text_two_column',
      'create paragraph content transaction_grid',
      'create paragraph content upcoming_events',
      'create paragraph content user_action',
      'create paragraph content video',
      'delete paragraph content 3_column_w_image',
			'delete paragraph content bid',
			'delete paragraph content bos_signup_emergency_alerts',
			'delete paragraph content bos311',
			'delete paragraph content cabinet',
			'delete paragraph content card',
			'delete paragraph content city_score_dashboard',
			'delete paragraph content custom_hours_text',
			'delete paragraph content daily_hours',
			'delete paragraph content discussion_topic',
			'delete paragraph content document',
			'delete paragraph content drawer',
			'delete paragraph content drawers',
			'delete paragraph content election_results',
			'delete paragraph content external_link',
			'delete paragraph content featured_item',
			'delete paragraph content featured_topics',
			'delete paragraph content feedback',
			'delete paragraph content fyi',
			'delete paragraph content gol_list_links',
			'delete paragraph content grid_of_cards',
			'delete paragraph content grid_of_people',
			'delete paragraph content grid_of_places',
			'delete paragraph content grid_of_programs_initiatives',
			'delete paragraph content grid_of_quotes',
			'delete paragraph content grid_of_topics',
			'delete paragraph content group_of_links_grid',
			'delete paragraph content group_of_links_list',
			'delete paragraph content group_of_links_mini_grid',
			'delete paragraph content header_text',
			'delete paragraph content hero_image',
			'delete paragraph content how_to_contact_step',
			'delete paragraph content how_to_tab',
			'delete paragraph content how_to_text_step',
			'delete paragraph content iframe',
			'delete paragraph content internal_l$nk',
			'delete paragraph content list',
			'delete paragraph content map',
			'delete paragraph content map_coordinates',
			'delete paragraph content map_esri_feed',
			'delete paragraph content map_pin',
			'delete paragraph content message_for_the_day',
			'delete paragraph content news_announcements',
			'delete paragraph content newsletter',
			'delete paragraph content photo',
			'delete paragraph content quote',
			'delete paragraph content recollect_widget',
			'delete paragraph content script_embed',
			'delete paragraph content seamless_doc',
			'delete paragraph content sidebar_item',
			'delete paragraph content sidebar_item_w_icon',
			'delete paragraph content social_media_links',
			'delete paragraph content social_networking',
			'delete paragraph content status_override',
			'delete paragraph content tabbed_content_tab',
			'delete paragraph content text',
			'delete paragraph content text_one_column',
			'delete paragraph content text_three_column',
			'delete paragraph content text_two_column',
			'delete paragraph content transaction_grid',
			'delete paragraph content upcoming_events',
			'delete paragraph content user_action',
			'delete paragraph content video',
      'update paragraph content 3_column_w_image',
      'update paragraph content bid',
      'update paragraph content bos_signup_emergency_alerts',
      'update paragraph content bos311',
      'update paragraph content cabinet',
      'update paragraph content card',
      'update paragraph content city_score_dashboard',
      'update paragraph content custom_hours_text',
      'update paragraph content daily_hours',
      'update paragraph content discussion_topic',
      'update paragraph content document',
      'update paragraph content drawer',
      'update paragraph content drawers',
      'update paragraph content election_results',
      'update paragraph content external_link',
      'update paragraph content featured_item',
      'update paragraph content featured_topics',
      'update paragraph content feedback',
      'update paragraph content fyi',
      'update paragraph content gol_list_links',
      'update paragraph content grid_of_cards',
      'update paragraph content grid_of_people',
      'update paragraph content grid_of_places',
      'update paragraph content grid_of_programs_initiatives',
      'update paragraph content grid_of_quotes',
      'update paragraph content grid_of_topics',
      'update paragraph content group_of_links_grid',
      'update paragraph content group_of_links_list',
      'update paragraph content group_of_links_mini_grid',
      'update paragraph content header_text',
      'update paragraph content hero_image',
      'update paragraph content how_to_contact_step',
      'update paragraph content how_to_tab',
      'update paragraph content how_to_text_step',
      'update paragraph content iframe',
      'update paragraph content internal_link',
      'update paragraph content list',
      'update paragraph content map',
      'update paragraph content map_coordinates',
      'update paragraph content map_esri_feed',
      'update paragraph content map_pin',
      'update paragraph content message_for_the_day',
      'update paragraph content news_announcements',
      'update paragraph content newsletter',
      'update paragraph content photo',
      'update paragraph content quote',
      'update paragraph content recollect_widget',
      'update paragraph content script_embed',
      'update paragraph content seamless_doc',
      'update paragraph content sidebar_item',
      'update paragraph content sidebar_item_w_icon',
      'update paragraph content social_media_links',
      'update paragraph content social_networking',
      'update paragraph content status_override',
      'update paragraph content tabbed_content_tab',
      'update paragraph content text',
      'update paragraph content text_one_column',
      'update paragraph content text_three_column',
      'update paragraph content text_two_column',
      'update paragraph content transaction_grid',
      'update paragraph content upcoming_events',
      'update paragraph content user_action',
      'update paragraph content video',
      'use workbench_moderation my drafts tab',
      'view files',
      'view all unpublished content',
      'view the administration theme',
      'view revisions',
      'vote on polls',
    ),
    // Site Administrator role permissions.
    'Site Administrator' => array(
      'access media browser',
      'access workbench',
      'administer custom tokens',
      'administer keyboard shortcuts',
      'administer media wysiwyg view mode',
      'administer menu',
      'administer taxonomy',
      'bypass rh_file',
      'bypass rh_node',
      'bypass rh_taxonomy',
      'create advpoll content',
      'create article content',
      'create department_profile content',
      'create emergency_alert content',
      'create event content',
      'create files',
      'create how_to content',
      'create landing_page content',
      'create listing_page content',
      'create person_profile content',
      'create place_profile content',
      'create post content',
      'create program_initiative_profile content',
      'create public_notice content',
      'create script_page content',
      'create status_item content',
      'create topic_page content',
      'create transaction content',
      'create url aliases',
      'delete any advpoll content',
      'delete any article content',
      'delete any department_profile content',
      'delete any emergency_alert content',
      'delete any event content',
      'delete any how_to content',
      'delete any landing_page content',
      'delete any listing_page content',
      'delete any person_profile content',
      'delete any place_profile content',
      'delete any post content',
      'delete any program_initiative_profile content',
      'delete any public_notice content',
      'delete any script_page content',
      'delete any status_item content',
      'delete any topic_page content',
      'delete any transaction content',
      'delete own advpoll content',
      'delete own article content',
      'delete own department_profile content',
      'delete own emergency_alert content',
      'delete own event content',
      'delete own how_to content',
      'delete own landing_page content',
      'delete own listing_page content',
      'delete own person_profile content',
      'delete own place_profile content',
      'delete own post content',
      'delete own program_initiative_profile content',
      'delete own script_page content',
      'delete own status_item content',
      'delete own topic_page content',
      'delete own transaction content',
			'delete paragraph content 3_column_w_image',
			'delete paragraph content bid',
			'delete paragraph content bos_signup_emergency_alerts',
			'delete paragraph content bos311',
			'delete paragraph content cabinet',
			'delete paragraph content card',
			'delete paragraph content city_score_dashboard',
			'delete paragraph content custom_hours_text',
			'delete paragraph content daily_hours',
			'delete paragraph content discussion_topic',
			'delete paragraph content document',
			'delete paragraph content drawer',
			'delete paragraph content drawers',
			'delete paragraph content election_results',
			'delete paragraph content external_link',
			'delete paragraph content featured_item',
			'delete paragraph content featured_topics',
			'delete paragraph content feedback',
			'delete paragraph content fyi',
			'delete paragraph content gol_list_links',
			'delete paragraph content grid_of_cards',
			'delete paragraph content grid_of_people',
			'delete paragraph content grid_of_places',
			'delete paragraph content grid_of_programs_initiatives',
			'delete paragraph content grid_of_quotes',
			'delete paragraph content grid_of_topics',
			'delete paragraph content group_of_links_grid',
			'delete paragraph content group_of_links_list',
			'delete paragraph content group_of_links_mini_grid',
			'delete paragraph content header_text',
			'delete paragraph content hero_image',
			'delete paragraph content how_to_contact_step',
			'delete paragraph content how_to_tab',
			'delete paragraph content how_to_text_step',
			'delete paragraph content iframe',
			'delete paragraph content internal_l$nk',
			'delete paragraph content list',
			'delete paragraph content map',
			'delete paragraph content map_coordinates',
			'delete paragraph content map_esri_feed',
			'delete paragraph content map_pin',
			'delete paragraph content message_for_the_day',
			'delete paragraph content news_announcements',
			'delete paragraph content newsletter',
			'delete paragraph content photo',
			'delete paragraph content quote',
			'delete paragraph content recollect_widget',
			'delete paragraph content script_embed',
			'delete paragraph content seamless_doc',
			'delete paragraph content sidebar_item',
			'delete paragraph content sidebar_item_w_icon',
			'delete paragraph content social_media_links',
			'delete paragraph content social_networking',
			'delete paragraph content status_override',
			'delete paragraph content tabbed_content_tab',
			'delete paragraph content text',
			'delete paragraph content text_one_column',
			'delete paragraph content text_three_column',
			'delete paragraph content text_two_column',
			'delete paragraph content transaction_grid',
			'delete paragraph content upcoming_events',
			'delete paragraph content user_action',
			'delete paragraph content video',
      'delete revisions',
      'delete terms in contact',
      'delete terms in event_type',
      'delete terms in neighborhoods',
      'delete terms in political_party',
      'delete terms in profile_type',
      'delete terms in program_type',
      'delete terms in place_type',
      'delete terms in features',
      'delete terms in icons',
      'delete terms in topic_category',
      'delete terms in news_tags',
      'delete terms in holidays',
      'edit any advpoll content',
      'edit any article content',
      'edit any department_profile content',
      'edit any emergency_alert content',
      'edit any event content',
      'edit any how_to content',
      'edit any image files',
      'edit any landing_page content',
      'edit any listing_page content',
      'edit any person_profile content',
      'edit any place_profile content',
      'edit any post content',
      'edit any program_initiative_profile content',
      'edit any public_notice content',
      'edit any script_page content',
      'edit any status_item content',
      'edit any topic_page content',
      'edit any transaction content',
      'edit meta tags',
      'edit own advpoll content',
      'edit own article content',
      'edit own department_profile content',
      'edit own emergency_alert content',
      'edit own event content',
      'edit own how_to content',
      'edit own image files',
      'edit own landing_page content',
      'edit own listing_page content',
      'edit own person_profile content',
      'edit own place_profile content',
      'edit own post content',
      'edit own program_initiative_profile content',
      'edit own script_page content',
      'edit own status_item content',
      'edit own topic_page content',
      'edit own transaction content',
      'edit terms in contact',
      'edit terms in event_type',
      'edit terms in neighborhoods',
      'edit terms in political_party',
      'edit terms in profile_type',
      'edit terms in program_type',
      'edit terms in place_type',
      'edit terms in features',
      'edit terms in icons',
      'edit terms in topic_category',
      'edit terms in news_tags',
      'edit terms in holidays',
      'list custom tokens',
      'moderate content from archive to draft',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from needs_review to published',
      'moderate content from published to archive',
      'moderate content from published to draft',
      'revert revisions',
      'set any workbench schedule',
      'set workbench schedule for schedule',
      'set workbench schedule for unpublish',
			'update paragraph content 3_column_w_image',
			'update paragraph content bid',
			'update paragraph content bos_signup_emergency_alerts',
			'update paragraph content bos311',
			'update paragraph content cabinet',
			'update paragraph content card',
			'update paragraph content city_score_dashboard',
			'update paragraph content custom_hours_text',
			'update paragraph content daily_hours',
			'update paragraph content discussion_topic',
			'update paragraph content document',
			'update paragraph content drawer',
			'update paragraph content drawers',
			'update paragraph content election_results',
			'update paragraph content external_link',
			'update paragraph content featured_item',
			'update paragraph content featured_topics',
			'update paragraph content feedback',
			'update paragraph content fyi',
			'update paragraph content gol_list_links',
			'update paragraph content grid_of_cards',
			'update paragraph content grid_of_people',
			'update paragraph content grid_of_places',
			'update paragraph content grid_of_programs_initiatives',
			'update paragraph content grid_of_quotes',
			'update paragraph content grid_of_topics',
			'update paragraph content group_of_links_grid',
			'update paragraph content group_of_links_list',
			'update paragraph content group_of_links_mini_grid',
			'update paragraph content header_text',
			'update paragraph content hero_image',
			'update paragraph content how_to_contact_step',
			'update paragraph content how_to_tab',
			'update paragraph content how_to_text_step',
			'update paragraph content iframe',
			'update paragraph content internal_link',
			'update paragraph content list',
			'update paragraph content map',
			'update paragraph content map_coordinates',
			'update paragraph content map_esri_feed',
			'update paragraph content map_pin',
			'update paragraph content message_for_the_day',
			'update paragraph content news_announcements',
			'update paragraph content newsletter',
			'update paragraph content photo',
			'update paragraph content quote',
			'update paragraph content recollect_widget',
			'update paragraph content script_embed',
			'update paragraph content seamless_doc',
			'update paragraph content sidebar_item',
			'update paragraph content sidebar_item_w_icon',
			'update paragraph content social_media_links',
			'update paragraph content social_networking',
			'update paragraph content status_override',
			'update paragraph content tabbed_content_tab',
			'update paragraph content text',
			'update paragraph content text_one_column',
			'update paragraph content text_three_column',
			'update paragraph content text_two_column',
			'update paragraph content transaction_grid',
			'update paragraph content upcoming_events',
			'update paragraph content user_action',
			'update paragraph content video',
      'use media wysiwyg',
      'use text format filtered_html',
      'use text format full_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'use workbench_scheduler scheduled content tab',
      'view all unpublished content',
      'view any workbench schedule',
      'view moderation history',
      'view moderation messages',
      'view own files',
      'view own private files',
      'view own unpublished content',
      'view revisions',
      'view schedule history',
    ),
    // Content Editor role permissions.
    'Content Editor' => array(
      'access media browser',
      'access workbench',
      'administer media wysiwyg view mode',
      'create article content',
      'create department_profile content',
      'create event content',
      'create files',
      'create how_to content',
      'create person_profile content',
      'create place_profile content',
      'create post content',
      'create program_initiative_profile content',
      'edit any article content',
      'edit any department_profile content',
      'edit any event content',
      'edit any how_to content',
      'edit any image files',
      'edit any person_profile content',
      'edit any place_profile content',
      'edit any post content',
      'edit any program_initiative_profile content',
      'edit meta tags',
      'edit own article content',
      'edit own department_profile content',
      'edit own event content',
      'edit own how_to content',
      'edit own image files',
      'edit own person_profile content',
      'edit own place_profile content',
      'edit own post content',
      'edit own program_initiative_profile content',
      'moderate content from archive to draft',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from needs_review to published',
      'moderate content from published to archive',
      'moderate content from published to draft',
      'revert revisions',
      'set any workbench schedule',
      'set workbench schedule for schedule',
      'set workbench schedule for unpublish',
      'use media wysiwyg',
      'use text format filtered_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'use workbench_scheduler scheduled content tab',
      'view all unpublished content',
      'view any workbench schedule',
      'view moderation history',
      'view moderation messages',
      'view own files',
      'view own private files',
      'view own unpublished content',
      'view revisions',
      'view schedule history',
    ),
    // Landing Page Author role permissions.
    // Assumes user is at least a content author.
    'Landing Author' => array(
      'create landing_page content',
      'edit any landing_page content',
      'edit own landing_page content',
    ),
    // Guide Author role permissions.
    // Assumes user is at least a content author.
    'Guide Author' => array(
      'create topic_page content',
      'edit any topic_page content',
      'edit own topic_page content',
    ),
    // Content Author role permissions.
    'Content Author' => array(
      'access content',
      'access media browser',
      'access workbench',
      'administer media wysiwyg view mode',
      'create article content',
      'create department_profile content',
      'create event content',
      'create files',
      'create how_to content',
      'create person_profile content',
      'create place_profile content',
      'create public_notice content',
      'create post content',
      'create program_initiative_profile content',
      'create tabbed_content content',
      'edit any article content',
      'edit any department_profile content',
      'edit any event content',
      'edit any how_to content',
      'edit any image files',
      'edit any person_profile content',
      'edit any place_profile content',
      'edit any public_notice content',
      'edit any post content',
      'edit any program_initiative_profile content',
      'edit meta tags',
      'edit own article content',
      'edit own department_profile content',
      'edit own event content',
      'edit own how_to content',
      'edit own image files',
      'edit own listing_page content',
      'edit own person_profile content',
      'edit own place_profile content',
      'edit own post content',
      'edit own program_initiative_profile content',
      'edit own public_notice content',
      'edit own tabbed_content content',
      'moderate content from archive to draft',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from published to draft',
      'revert revisions',
      'use media wysiwyg',
      'use text format filtered_html',
      'use workbench_moderation my drafts tab',
      'view all unpublished content',
      'view moderation history',
      'view moderation messages',
      'view own files',
      'view own private files',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
    ),
    // Events Editor role permissions.
    'Events Editor' => array(
      'access media browser',
      'access workbench',
      'administer media wysiwyg view mode',
      'create event content',
      'create files',
      'edit any event content',
      'edit meta tags',
      'edit own event content',
      'moderate content from archive to draft',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from needs_review to published',
      'moderate content from published to archive',
      'moderate content from published to draft',
      'revert revisions',
      'set any workbench schedule',
      'set workbench schedule for schedule',
      'set workbench schedule for unpublish',
      'use media wysiwyg',
      'use text format filtered_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'use workbench_scheduler scheduled content tab',
      'view all unpublished content',
      'view any workbench schedule',
      'view moderation history',
      'view moderation messages',
      'view own files',
      'view own private files',
      'view own unpublished content',
      'view revisions',
      'view schedule history',
    ),
    // Press Release Editor role permissions.
    'Press Release Editor' => array(
      'access media browser',
      'access workbench',
      'administer media wysiwyg view mode',
      'create files',
      'create post content',
      'edit any image files',
      'edit any post content',
      'edit meta tags',
      'edit own image files',
      'edit own post content',
      'moderate content from archive to draft',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from needs_review to published',
      'moderate content from published to archive',
      'moderate content from published to draft',
      'revert revisions',
      'set any workbench schedule',
      'set workbench schedule for schedule',
      'set workbench schedule for unpublish',
      'use media wysiwyg',
      'use text format filtered_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'use workbench_scheduler scheduled content tab',
      'view all unpublished content',
      'view any workbench schedule',
      'view moderation history',
      'view moderation messages',
      'view own files',
      'view own private files',
      'view own unpublished content',
      'view revisions',
      'view schedule history',
    ),
    // Status Alert Editor role permissions.
    'Status Alert Editor' => array(
      'access administration menu',
      'access administration pages',
      'access content',
      'access media browser',
      'access workbench',
      'bypass rh_node',
      'bypass workbench moderation',
      'create emergency_alert content',
      'create status_item content',
      'delete any emergency_alert content',
      'delete any status_item content',
      'delete own emergency_alert content',
      'delete own status_item content',
      'edit any emergency_alert content',
      'edit any status_item content',
      'edit meta tags',
      'edit own emergency_alert content',
      'edit own status_item content',
      'moderate content from archive to draft',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from needs_review to published',
      'moderate content from published to archive',
      'moderate content from published to draft',
      'revert revisions',
      'set any workbench schedule',
      'set workbench schedule for schedule',
      'set workbench schedule for unpublish',
      'use media wysiwyg',
      'use text format filtered_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'use workbench_scheduler scheduled content tab',
      'view all unpublished content',
      'view any workbench schedule',
      'view moderation history',
      'view moderation messages',
      'view own unpublished content',
      'view revisions',
      'view schedule history',
      'view the administration theme',
    ),
    // Developer role permissions.
    'Developer' => array(
      'access media browser',
      'access workbench',
      'administer media wysiwyg view mode',
      'administer menu',
      'administer taxonomy',
      'create advpoll content',
      'create article content',
      'create department_profile content',
      'create event content',
      'create files',
      'create how_to content',
      'create landing_page content',
      'create listing_page content',
      'create person_profile content',
      'create place_profile content',
      'create post content',
      'create program_initiative_profile content',
      'create status_item content',
      'create topic_page content',
      'create url aliases',
      'delete terms in contact',
      'delete terms in event_type',
      'delete terms in neighborhoods',
      'delete terms in political_party',
      'delete terms in profile_type',
      'delete terms in program_type',
      'delete terms in place_type',
      'delete terms in features',
      'delete terms in icons',
      'delete terms in topic_category',
      'delete terms in news_tags',
      'delete terms in holidays',
      'edit any advpoll content',
      'edit any article content',
      'edit any department_profile content',
      'edit any event content',
      'edit any how_to content',
      'edit any image files',
      'edit any landing_page content',
      'edit any listing_page content',
      'edit any person_profile content',
      'edit any place_profile content',
      'edit any post content',
      'edit any program_initiative_profile content',
      'edit any status_item content',
      'edit any topic_page content',
      'edit meta tags',
      'edit own advpoll content',
      'edit own article content',
      'edit own department_profile content',
      'edit own event content',
      'edit own how_to content',
      'edit own image files',
      'edit own landing_page content',
      'edit own listing_page content',
      'edit own person_profile content',
      'edit own place_profile content',
      'edit own post content',
      'edit own program_initiative_profile content',
      'edit own status_item content',
      'edit own topic_page content',
      'edit terms in contact',
      'edit terms in event_type',
      'edit terms in neighborhoods',
      'edit terms in political_party',
      'edit terms in profile_type',
      'edit terms in program_type',
      'edit terms in place_type',
      'edit terms in features',
      'edit terms in icons',
      'edit terms in topic_category',
      'edit terms in news_tags',
      'edit terms in holidays',
      'moderate content from archive to draft',
      'moderate content from draft to needs_review',
      'moderate content from needs_review to draft',
      'moderate content from needs_review to published',
      'moderate content from published to archive',
      'moderate content from published to draft',
      'revert revisions',
      'use media wysiwyg',
      'use text format filtered_html',
      'use text format full_html',
      'use workbench_moderation my drafts tab',
      'use workbench_moderation needs review tab',
      'view all unpublished content',
      'view moderation history',
      'view moderation messages',
      'view own files',
      'view own private files',
      'view own unpublished content',
      'view revisions',
    ),
  );
}
