<?php
/**
 * @file
 * Code for the Boston Calendar View feature.
 */

include_once 'bos_view_calendar_listing.features.inc';


/**
 * Implements hook_preprocess_views_exposed_form().
 */
function bos_view_calendar_listing_preprocess_views_exposed_form(&$vars) {
  if ($vars['form']['#id'] == 'views-exposed-form-calendar-listing') {
    $vars['widget_groups'] = array(
      'dates' => array(),
      'title' => array(),
      'event type' => array(),
      'neighborhood' => array(),
    );

    foreach ($vars['widgets'] as $id => $widget) {
      switch ($id) {
        case 'filter-field_event_dates_value':
        case 'filter-field_event_dates_value2':
          $vars['widget_groups']['dates'][$id] = $widget;
          break;

        case 'filter-title':
          $vars['widget_groups']['title'][$id] = $widget;
          break;

        case 'filter-field_multiple_neighborhoods_target_id':
          $vars['widget_groups']['neighborhood'][$id] = $widget;
          break;

        case 'filter-field_event_type_target_id':
          $vars['widget_groups']['event type'][$id] = $widget;
          break;

        case 'filter-field_related_departments_target_id':
          $vars['widget_groups']['department'][$id] = $widget;
          break;
      }
    }
  }
}
