<?php
/**
 * @file
 * Code for the Boston Component Cabinet feature.
 */

include_once 'bos_component_cabinet.features.inc';

/**
 * Implements hook_preprocess_entity().
 */
function bos_component_cabinet_preprocess_entity(&$variables, $hook) {
  if ($variables['entity_type'] === 'paragraphs_item' &&
      $variables['paragraphs_item']->bundle == 'cabinet') {
    // For Cabinet, convert the list of contacts to be a UL.
    if (!empty($variables['elements']['field_contacts'])) {
      $title = '';
      $type = 'ul';
      $attributes = array(
        'class' => 'ul t--upper t--sans',
      );

      $contacts = field_get_items('paragraphs_item', $variables['paragraphs_item'], 'field_contacts');
      $contact_items = array();

      foreach ($contacts as $key => $contact) {
        $name = $contact["entity"]->name;
        $id = $contact["entity"]->field_department_profile["und"][0]["target_id"];

        if (isset($name) && isset($id)) {
          $url = drupal_get_path_alias("node/${id}");
          $contact_items[] = array(
            'data' => "<a href='/${url}'>${name}</a>",
            'class' => array('t--s100 lh--200'),
          );
        }
      }

      $cabinet_contacts = theme_item_list(array(
        'items' => $contact_items,
        'title' => $title,
        'type' => $type,
        'attributes' => $attributes,
      ));
      $variables['cabinet_contacts'] = $cabinet_contacts;
    }
  }
}
