<?php

/**
 * @file
 * Establishes navigation for Paragraph Reference Manager.
 */

/**
 * Implements hook_menu().
 */
function paragraph_reference_manager_menu() {
  $items = array();
  $items['admin/structure/paragraphs/%/manage-references'] = array(
    'title' => 'Manage References',
    'page callback' => 'paragraph_reference_manager_admin',
    'access arguments' => array('administer paragraphs bundles'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
    'file' => 'paragraph_reference_manager.admin.inc',
    'file path' => drupal_get_path('module', 'paragraph_reference_manager'),
  );
  return $items;
}
