<?php

/**
 * @file
 * This module adds a 'Term Reference' mapper to the Salesforce Mapping module.
 */

module_load_include('inc', 'salesforce_term_ref', 'includes/salesforce_term_ref.fieldmap_type');

/**
 * Implements hook_salesforce_pull_entity_value_alter().
 */
function salesforce_term_ref_salesforce_pull_entity_value_alter(&$value, $field_map, $sf_object) {
  if (salesforce_term_ref_is_term_ref($field_map)) {
    salesforce_term_ref_handle_related_entity($value, $field_map, $sf_object);
  }
}

/**
 * Checks that the term_ref mapper has been selected.
 *
 * @param array $field_map
 *   Contains information about the mapper type.
 *
 * @return bool
 *   Returns true if term_ref was selected.
 */
function salesforce_term_ref_is_term_ref($field_map) {
  return $field_map['drupal_field']['fieldmap_type'] == 'term_ref';
}

/**
 * Handler for SF object.
 *
 * @param array $value
 *   Contains string with tid.
 * @param array $field_map
 *   Holds info about type of mapper and mapped field.
 * @param array $sf_object
 *   Contains information coming from Salesforce.
 */
function salesforce_term_ref_handle_related_entity(&$value, $field_map, $sf_object) {
  $field_info_field = salesforce_term_ref_get_drupal_field_info($field_map);
  $vocabulary = salesforce_term_ref_load_vocabulary($field_info_field);
  if (isset($vocabulary)) {
    $sf_picklist_str = salesforce_term_ref_get_sf_field_value($field_map, $sf_object);
    if (!empty($sf_picklist_str)) {
      $sf_picklist_values = explode(SALESFORCE_MAPPING_ARRAY_DELIMITER, $sf_picklist_str);
      $terms = array();
      foreach ($sf_picklist_values as $picklist_value) {
        $term = salesforce_term_ref_create_or_load_term($picklist_value, $vocabulary);
        if (isset($term)) {
          $terms[] = $term;
        }
      }
      $value = salesforce_term_ref_make_array_of_term_ids($terms);
      if ($field_info_field['cardinality'] == 1) {
        $value = reset($value);
      }
    }
  }
}

/**
 * Get data about the field itself.
 *
 * @param $field_map
 *
 * @return bool|mixed|void
 */
function salesforce_term_ref_get_drupal_field_info($field_map) {
  $drupal_field = salesforce_term_ref_get_drupal_field_name($field_map);
  return field_info_field($drupal_field);
}

/**
 * Creates a string value for the mapper name to be used to get field info.
 *
 * @param $field_map
 *   Contains information about the mapper.
 *
 * @return string
 *   Returns the name of the fieldmap.
 */
function salesforce_term_ref_get_drupal_field_name($field_map) {
  return $field_map['drupal_field']['fieldmap_value'];
}

/**
 * Load referenced vocabulary.
 *
 * @param $field_info_field
 *   Use to get machine name for vocabulary.
 *
 * @return mixed
 */
function salesforce_term_ref_load_vocabulary($field_info_field) {
  $vocabulary = null;
  $vocabularyName = array_keys($field_info_field['settings']['handler_settings']['target_bundles']);
  if (isset($vocabularyName)) {
    $vocabulary = taxonomy_vocabulary_machine_name_load($vocabularyName);
  }
  return $vocabulary;
}

/**
 * Get field value from Salesforce.
 *
 * @param array $field_map
 * @param array $sf_object
 */
function salesforce_term_ref_get_sf_field_value($field_map, $sf_object) {
  $sf_field = $field_map['salesforce_field']['name'];
  $sf_value = $sf_object[$sf_field];
  return $sf_value;
}

/**
 * Save the appropriate term to the referenced content type.
 *
 * @param string $picklist_value
 *   Is term title.
 * @param obj $vocabulary
 *   Holds details about the vocabulary.
 *
 * @return array|mixed|null
 */
function salesforce_term_ref_create_or_load_term($picklist_value, $vocabulary) {
  $term = null;
  if (!empty($picklist_value)) {
    $existing_terms = taxonomy_get_term_by_name($picklist_value, $vocabulary->machine_name);
    if (empty($existing_terms)) {
      $term = salesforce_term_ref_create_new_term($vocabulary, $picklist_value);
    } else {
      $term = reset($existing_terms);
    }
  }
  return $term;
}

/**
 * Add term to taxonomy if not found.
 *
 * @param obj $vocabulary
 *   Contains details about the vocabulary.
 * @param $term_name
 *
 * @return array
 */
function salesforce_term_ref_create_new_term($vocabulary, $term_name) {
  $new_term = new stdClass();
  $new_term->vid = $vocabulary->vid;
  $new_term->name = $term_name;
  $new_term->format = 'plain_text';
  $new_term->description = 'This term came directly from Salesforce.';
  taxonomy_term_save($new_term);
  return $new_term;
}

/**
 * Creates an array of tids.
 *
 * @param $terms
 *
 * @return array
 */
function salesforce_term_ref_make_array_of_term_ids($terms) {
  $term_ids = array();
  foreach ($terms as $new_term) {
    $term_ids[] = $new_term->tid;
  }
  return $term_ids;
}
