<?php

/**
 * @file
 * Library for connecting to Swiftype.
 */

require 'lib/swiftype.php';

/**
 * Implements hub_swiftype_menu().
 */
function hub_swiftype_menu() {
  $items = array();

  // The path that the endpoint will be registered to.
  $items['search'] = array(
    'title' => 'Search',
    // The name of the function called when the path is accessed.
    'page callback' => 'hub_swiftype_search_page_callback',
    // Set this value to TRUE to allow access to any user.
    'access callback' => TRUE,
    // Declare this as a simple registered path.
    'type' => MENU_CALLBACK,
  );

  // Return the $items array to register the path.
  return $items;
}

/**
 * Implements hub_swiftype_search_page_callback().
 */
function hub_swiftype_search_page_callback() {
  $params = drupal_get_query_parameters();

  $client = new \Swiftype\SwiftypeClient(variable_get('swiftype_email'), variable_get('swiftype_password'), variable_get('swiftype_key'));

  if ($params['query']) {
    $results = $client->search('the-hub', 'page', $params['query'], array(
      'per_page' => 10,
      'page' => $params['page'] ? $params['page'] : 1,
      'facets' => array(
        'page' => array(
          'type',
        ),
      ),
    ));
  }
  else {
    $results = NULL;
  }

  return theme('hub_swiftype_search_results', array(
    'results' => $results,
    'range'   => hub_swiftype_page_range($results['body']->info->page),
    'selected_facets' => $params['facet'] ? $params['facet'] : array(),
  ));
}

/**
 * Implements hub_swiftype_theme().
 */
function hub_swiftype_theme() {
  return array(
    'hub_swiftype_search_results' => array(
      'template' => 'theme/search-results',
      'variables' => array(
        'results' => NULL,
        'range'   => range(1, 5),
        'selected_facets' => array(),
      ),
    ),
  );
}

/**
 * Implements hub_swiftype_page_range().
 */
function hub_swiftype_page_range($info) {
  $start = 1;
  $end = 5;

  if ($info->current_page > 5) {
    $start = $info->current_page - 2;
    $end = $info->current_page + 2;
  }

  if ($info->num_pages < 5) {
    $end = $info->num_pages;
  }

  return range($start, $end);
}

/**
 * Implements hub_swiftype_facet_type().
 */
function hub_swiftype_facet_type($type) {
  $facets = array(
    'department_profile' => 'Departments',
    'event' => 'Events',
    'article' => 'Articles',
    'how_to' => 'How-Tos',
    'topic_page' => 'Guides',
  );

  return $facets[$type] ? $facets[$type] : FALSE;
}
