<?php
/**
 * @file
 * Code for the bos_view_blank_layouts feature.
 */

include_once 'bos_view_blank_layouts.features.inc';

/**
 * Implements hook_preprocess_views_exposed_form().
 */
function bos_view_blank_layouts_preprocess_views_view(&$vars) {
  if ($vars["view"]->name == 'blank_layouts') {
    $element = array(
      '#tag' => 'base',
      '#attributes' => array(
        'href' => $GLOBALS['base_url'],
      ),
    );
    drupal_add_html_head($element, 'base_tag');
  }
}
