<?php
/**
 * @file
 * Code for the bos_view_public_notice feature.
 */

include_once 'bos_view_public_notice.features.inc';

/**
 * Implements hook_preprocess_views_exposed_form().
 */
function bos_view_public_notice_preprocess_views_exposed_form(&$vars) {
  if ($vars['form']['#id'] == 'views-exposed-form-public-notice-landing' || $vars['form']['#id'] == 'views-exposed-form-public-notice-archive') {
    $vars['widget_groups'] = array(
      'search by title' => array(),
      'filter by department' => array(),
    );

    foreach ($vars['widgets'] as $id => $widget) {
      switch ($id) {
        case 'filter-title':
          $vars['widget_groups']['search by title'][$id] = $widget;
          break;

        case 'filter-field_contact_target_id':
          $vars['widget_groups']['filter by department'][$id] = $widget;
          break;
      }
    }
  }
}
