<?php
/**
 * @file
 * Drupal needs this blank file.
 */

 /**
  * Implements metatag_metatags_view_alter().
  */
function bos_meta_tags_metatag_metatags_view_alter(&$output, $instance) {
  if ($output["article:published_time"] && $output["article:published_time"]["#attached"]["drupal_add_html_head"][0][0]) {
    $tag = $output["article:published_time"]["#attached"]["drupal_add_html_head"][0][0];

    $output["article:published_time"] = NULL;

    $published_at_element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'class' => 'swiftype',
        'name' => 'published_at',
        'data-type' => 'date',
        'content' => $tag['#value'],
      ),
    );
    drupal_add_html_head($published_at_element, 'swiftype_published_at');
  }

  if ($output["article:modified_time"] && $output["article:modified_time"]["#attached"]["drupal_add_html_head"][0][0]) {
    $tag = $output["article:modified_time"]["#attached"]["drupal_add_html_head"][0][0];

    $output["article:modified_time"] = NULL;

    $modified_at_element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'class' => 'swiftype',
        'name' => 'modified_at',
        'data-type' => 'date',
        'content' => $tag['#value'],
      ),
    );
    drupal_add_html_head($modified_at_element, 'swiftype_modified_at');
  }

  if ($output["description"] && $output["description"]["#attached"]["drupal_add_html_head"][0][0]) {
    $tag = $output["description"]["#attached"]["drupal_add_html_head"][0][0];

    $output["description"] = NULL;

    $description_element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'class' => 'swiftype',
        'name' => 'description',
        'data-type' => 'text',
        'content' => $tag['#value'],
      ),
    );
    drupal_add_html_head($description_element, 'swiftype_description');
  }
}
