<?php

/**
 * @file
 * Adds "citywide" option to field_multiple_neighborhoods.
 */

/**
 * Implements form_alter().
 */
function bos_form_citywide_neighborhood_form_alter(&$form, &$form_state, $form_id) {
  // Make sure we're on an Event, Post, or Public Notice form.
  if (($form_id == "event_node_form") || ($form_id == "post_node_form") || ($form_id == "notice_node_form")) {
    // Create a new checkbox call 'Citywide'.
    $form['field_multiple_neighborhoods'][LANGUAGE_NONE]['#options']['citywide'] = 'Citywide';
    // Set the weight so the 'Citywide' option appears at the top of the list.
    $form['field_multiple_neighborhoods'][LANGUAGE_NONE]['citywide']['#weight'] = -99;
    // Loop through every Neighborhood checkbox.
    foreach ($form['field_multiple_neighborhoods'][LANGUAGE_NONE]['#options'] as $tid => $name) {
      // Set a state for all checkbox based on 'Citywide' value.
      $form['field_multiple_neighborhoods'][LANGUAGE_NONE][$tid]['#states'] = array(
        'checked' => array(
          ':input[name="field_multiple_neighborhoods[und][citywide]"]' => array('checked' => TRUE),
        ),
      );
    }
  }
}

/**
 * Implements hook_page_build().
 */
function bos_form_citywide_neighborhood_page_build(&$page) {
  // Load the node we're on.
  if ($node = menu_get_object()) {
    // Get the node ID.
    $nid = $node->nid;
  }
  // Get the content type.
  $bundle = $page['content']['system_main']['nodes'][$nid]['#bundle'];
  // Make sure we only run this code on certain content types.
  if ($bundle == 'event' || $bundle == 'post' || $bundle == 'notice') {
    if (FALSE) { // Needs to look for 'citywide value'
      $neighborhoods = $page['content']['system_main']['nodes'][$nid]['field_multiple_neighborhoods'];
      foreach ($neighborhoods as $key => $neighborhood) {
        if (is_numeric($key)) {
          unset($page['content']['system_main']['nodes'][$nid]['field_multiple_neighborhoods'][$key]);
        }
      }
      $page['content']['system_main']['nodes'][$nid]['field_multiple_neighborhoods'][0]['#markup'] = 'Citywide';
    }
  }
}
