<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_menu_block_tree_alter().
 */
function bos_menu_main_menu_menu_block_tree_alter(&$tree, $config) {
  if ($config['menu_name'] === 'main-menu') {
  }
}

/**
 * Implements hook_block_view_alter().
 */
function bos_menu_main_menu_block_view_alter(&$data, $block) {
  if (isset($data['content']['#config']['menu_name']) && $data['content']['#config']['menu_name'] === 'main-menu') {
    // As long as we are working with a menu block render array, then check each
    // first-level menu item to see if it's a secondary menu item. If it is
    // attach a class identifying it as such so that it can be targeted.
    foreach ($data['content']['#content'] as $mlid => &$link_render) {
      if (!empty($link_render['#title']) && strpos($link_render['#title'], '311') !== FALSE) {
        $link_render['#attributes']['class'][] = 'nv-m-c-a--y';
      }
      if (!empty($link_render['#title']) && strpos($link_render['#title'], 'Log In') !== FALSE) {
        $link_render['#attributes']['class'][] = 'login-link';
      }
    }
  }
}
