<?php

/**
 * @file
 * Code for the Boston Commissions Search feature.
 */

/**
 * Implements hook_preprocess_entity().
 */
function bos_commissions_search_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['elements']['#bundle'] == 'commissions_search') {
      $commissions_graphql_api_key = variable_get('commissions_graphql_api_key');
      $commissions_graphql_endpoint = variable_get('commissions_graphql_endpoint');

      drupal_add_js(
        array(
          'bos_commissions_search' => array(
            'bos_commissions_search_graphql_api_key' => $commissions_graphql_api_key,
          ),
        ),
        array('type' => 'setting')
      );
      drupal_add_js(
        array(
          'bos_commissions_search' => array(
            'bos_commissions_search_graphql_endpoint' => $commissions_graphql_endpoint,
          ),
        ),
        array('type' => 'setting')
      );
    }
  }
}
