<?php
/**
 * @file
 * Code for the Boston Metrolist Affordable Housing Listing feature.
 */

include_once 'bos_metrolist_affordable_housing.features.inc';

/**
 * Implements hook_preprocess_views_exposed_form().
 */
function bos_metrolist_affordable_housing_preprocess_views_exposed_form(&$vars) {
  if ($vars['form']['#id'] == 'views-exposed-form-metrolist-affordable-housing-page') {
    $vars['widget_groups'] = array(
      'key words' => array(),
      'neighborhood' => array(),
    );

    foreach ($vars['widgets'] as $id => $widget) {
      switch ($id) {

        case 'filter-combine':
          $vars['widget_groups']['key words'][$id] = $widget;
          break;

        case 'filter-tid':
          $vars['widget_groups']['neighborhood'][$id] = $widget;
          break;
      }
    }
  }
}
