files:
  include: '**/*.s+(a|c)ss'
  ignore:
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-debug: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-warn: 1
  no-color-literals: 0
  no-color-keywords: 0
  no-duplicate-properties: 0
  no-css-comments: 0


  # Style Guide
  indentation: 0
  leading-zero: 1
  nesting-depth: 1
  property-sort-order: 0
  quotes: 0

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1

  empty-line-between-blocks: 0
  single-line-per-selector: 0
  empty-args: 0

  nesting-depth:
  - 1
  - max-depth: 3