<?php
/**
 * @file
 * bos_component_iframe.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function bos_component_iframe_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_iframe_size'.
  $field_bases['field_iframe_size'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_iframe_size',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        300 => '300px',
        480 => '480px',
        600 => '600px',
        0 => 'Auto',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_integer',
  );

  // Exported field_base: 'field_source_url'.
  $field_bases['field_source_url'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_source_url',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 400,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
