<?php
/**
 * @file
 * Code for the bos_view_api_public_notices feature.
 */

include_once 'bos_view_api_public_notices.features.inc';

/**
 * Implements hook_menu().
 */
function bos_view_api_public_notices_menu() {
  return [
    'api/v1/public-notices' => [
      'title' => 'public-notices',
      // The name of the function called when the path is accessed.
      'page callback' => 'bos_view_api_public_notices_endpoint',
      // Set this value to TRUE to allow access to any user.
      'access callback' => TRUE,
      // Declare this as a simple registered path.
      'type' => MENU_CALLBACK,
      ],
    ];
}

/**
 * Endpoint to return field_drawers as a correctly formatted array.
 */
function bos_view_api_public_notices_endpoint() {
  $headers = [
    "Status" => 200,
    "Cache-Control" => "max-age=60",
    "Content-Type" => "application/json; charset=utf-8'",
    "Expires" => format_date(strtotime("+1 minute"),"custom" , "D, d M Y H:i:s \G\M\T")
  ];

  $json = file_get_contents('http://localhost/api/v1/public-notices/view');

  if (!empty($json) && $json != "[]") {
    if ($json = json_decode($json)) {
      foreach ($json as &$notice) {
        if (!empty($notice->field_drawer)) {
          $drawers = explode('~', $notice->field_drawer);
          $notice->field_drawer = $drawers;
        }
      }
    }
    else {
      // Bad json from view.
      $headers['Status'] = "500";
      $json = [];
    }
  }
  else {
    // Nothing returned
    $headers['Status'] = "200";
    $json = [];
  }

  drupal_send_headers($headers);
  echo json_encode($json);

  exit;
}
