<?php
/**
 * @file
 * bos_component_vizwiz.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function bos_component_vizwiz_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'paragraphs_item-vizwiz-field_vizwiz'.
  $field_instances['paragraphs_item-vizwiz-field_vizwiz'] = array(
    'bundle' => 'vizwiz',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'markup',
        'settings' => array(),
        'type' => 'markup_default',
        'weight' => 1,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'fences_wrapper' => 'div_div_div',
    'field_name' => 'field_vizwiz',
    'label' => 'VizWiz',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'markup',
      'settings' => array(),
      'type' => 'markup',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'paragraphs_item-vizwiz-field_vizwiz_json'.
  $field_instances['paragraphs_item-vizwiz-field_vizwiz_json'] = array(
    'bundle' => 'vizwiz',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'paragraphs_editor_preview' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'paragraphs_item',
    'fences_wrapper' => 'div_div_div',
    'field_name' => 'field_vizwiz_json',
    'label' => 'VizWiz JSON',
    'required' => 0,
    'settings' => array(
      'linkit' => array(
        'button_text' => 'Search',
        'enable' => 0,
        'profile' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
        'show_token_tree' => 0,
      ),
      'type' => 'text_textarea',
      'weight' => 5,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('VizWiz');
  t('VizWiz JSON');

  return $field_instances;
}
